version: '2.2'
services:
  backend:
    image: my-back-server
    container_name: back-server
    restart: always
    expose:
      - "8080"
    environment:
      - TZ=Asia/Seoul
    #enf_file:
     # - ./MBTI-test-server/.env # 나중에 할 것
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
